In [4]:
import torch
import numpy as np

In [5]:

x=torch.empty(2,3)
x=torch.ones(1,3)
x=torch.rand(1,3)
x=torch.ones(2,2,dtype=torch.float16)
print(x.dtype)
print(x.size)
print(x)

torch.float16
<built-in method size of Tensor object at 0x00000259BAA9B250>
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [6]:
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [5]:
x=torch.rand(2,2)
print(x)

tensor([[0.6638, 0.5161],
        [0.6118, 0.0075]])


In [7]:
y=torch.rand(2,2)
print(y)

tensor([[0.6022, 0.3480],
        [0.1463, 0.6963]])


In [8]:
print(x+y)

tensor([[1.2660, 0.8641],
        [0.7581, 0.7038]])


In [9]:
y.add_(x)
print(y)

tensor([[1.2660, 0.8641],
        [0.7581, 0.7038]])


In [10]:
z=torch.div(x,y)
print(z)

tensor([[0.5243, 0.5973],
        [0.8070, 0.0107]])


Slicing 

In [11]:
x=torch.rand(5,3)
print(x)

tensor([[0.5352, 0.5282, 0.7567],
        [0.5393, 0.4702, 0.5244],
        [0.4645, 0.9008, 0.0695],
        [0.7435, 0.6389, 0.3599],
        [0.5760, 0.9261, 0.8692]])


In [12]:
###printing all rosw of column one
print(x[:,1])

tensor([0.5282, 0.4702, 0.9008, 0.6389, 0.9261])


In [13]:
### printing all columns of rows zero
print(x[0,:])

tensor([0.5352, 0.5282, 0.7567])


Coverting multidimensions to one dimension array

In [16]:
x=torch.rand(4,4)
print(x)
y=x.view(16)
print(y)# give 1x16 tensor
a=x.view(-1,8)
print(a) ## gives 2x8 tensor
print(a.size())

tensor([[0.8527, 0.7824, 0.4195, 0.9837],
        [0.0631, 0.4299, 0.9648, 0.8929],
        [0.6023, 0.5201, 0.3593, 0.6202],
        [0.0876, 0.5566, 0.8535, 0.0599]])
tensor([0.8527, 0.7824, 0.4195, 0.9837, 0.0631, 0.4299, 0.9648, 0.8929, 0.6023,
        0.5201, 0.3593, 0.6202, 0.0876, 0.5566, 0.8535, 0.0599])
tensor([[0.8527, 0.7824, 0.4195, 0.9837, 0.0631, 0.4299, 0.9648, 0.8929],
        [0.6023, 0.5201, 0.3593, 0.6202, 0.0876, 0.5566, 0.8535, 0.0599]])
torch.Size([2, 8])


In [19]:
if torch.cuda.is_available():
    device=torch.device('cuda')
    x=torch.oness(5,device=device)
    y=torch.ones(5)
    y=y.to(device)
    z=x+y
    z= z.to('cpu')  ## this will bring our tensor back to cpu
else:
    print('No cuda avilable')

No cuda avilable


### we can't convert gpu tensor back to numpy